default:
	javac *.java

run:
	java App

clean:
	rm -f *.class *.tar.gz
	reset
	clear

tar:
	tar -cvz CFG.java Node.java Edge.java Path.java List.java -f Code_Version_2.tar.gz

unzip:
	tar -zxvf *.tar